### ISSUE TITLE
Pipeline with parameter input cannot be triggered from UI

### ISSUE THREAD

**Issue by kandersen82** [openshift/tektoncd-pipeline-operator#146]
When creating a pipeline that uses a parameter, it is not possible to trigger a run from the UI. Clicking "Start" opens a popup to enter a parameter value, and clicking "Start" closes the popup and nothing happens. The pipeline can be triggered using the tkn-cli.

Versions:
OpenShift: 4.2
OpenShift Pipelines Operator: 0.8.1

Here is an example pipeline where i see the issue.
```
---
  apiVersion: tekton.dev/v1alpha1
  kind: Task
  metadata:
    name: echo-v3
  spec:
    inputs:
      params:
      - name: echoOutput
        type: string
        description: Stuff to echo
        default: "hello world!"
    steps:
      - name: echo
        image: ubuntu
        command: 
        - echo
        args:
        - "$(inputs.params.echoOutput)"
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: hello-world-pipeline-v3
spec:
  params:
    - name: saythis
      type: string
      description: Say this
      default: "Hello Universe!"
  tasks:
    - name: echo
      taskRef:
        name: echo-v3
      params:
        - name: echoOutput
          value: "$(params.saythis)"
```
