### ISSUE TITLE
Re-running pipelines in the OpenShift UI picks up default SA instead of the one last used

### ISSUE THREAD

**Issue by Cottonglow** [openshift/tektoncd-pipeline-operator#256]
**Problem:**
I have my own service account that I deploy to OpenShift along with the pipeline components. When I try and run the pipeline from the UI, there is no way to specify the service account I want to use and when I re-run an existing pipeline, the service account that was previously used for it, gets changed to the default service account.

**Expected:**
1. Be asked to specify service account to use, similar to how you are asked for the parameter values, when selecting `Start` on a pipeline on the `Pipelines` page.
2. Use the last specified service account when selecting `Rerun` on a pipeline on the `Pipeline Runs` page or when selecting `Start Last Run` on a pipeline on the `Pipelines` page.

**Steps to Reproduce:**
* Install the OpenShift Pipelines Operator from OperatorHub.
* Create a project called `test-pipelines`.
* Deploy the following resources:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-service-account
  namespace: test-pipelines
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: test-pipeline
  namespace: test-pipelines
spec:
  params:
    - name: message
      description: The message to echo
  tasks:
    - name: echo-message
      taskRef:
        name: echo
      params:
        - name: message
          value: "$(params.message)"
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: echo
  namespace: test-pipelines
spec:
  inputs:
    params:
      - name: message
        description: The message to echo
  steps:
    - name: output-message
      image: bash
      command: ["bash", "-c"]
      args:
        - echo -e '$(inputs.params.message)'
```
* When you try and run it from the UI, it will use the default service account.
* Deploy the pipelinerun from CLI:
```yaml
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: run-deploy-pipeline-
  namespace: test-pipelines
spec:
  serviceAccountName: test-service-account
  pipelineRef:
    name: test-pipeline
  params:
    - name: message
      value: "Hello World!"
```
* This will use the specified service account as expected.
* Re-run this pipeline from the UI.
* You will see in the `YAML` page, that the service account is changed to the default one.

**Versions:**
OpenShift: 4.3.0
OpenShift Pipelines Operator: 0.10.7
