### ISSUE TITLE
Release operator for v0.11 Tekton Pipelines release

### ISSUE THREAD

**Issue by booninite** [openshift/tektoncd-pipeline-operator#274]
I noticed v0.11.0 has been upstreamed into openshift/tektoncd-pipeline, but can't find any documentation on when we can expect it to be available via this operator.

With the given subscription, will I be upgraded to v0.11.0 when it is out?

```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator
  namespace: openshift-operators
spec:
  channel: canary
  name: openshift-pipelines-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
```
