### ISSUE TITLE
TaskRun: bound workspaces did not match declared workspaces

### ISSUE THREAD

**Issue by R-Lam** [openshift/tektoncd-pipeline-operator#409]
Trying to use maven as shown in [this blog](https://developers.redhat.com/blog/2020/02/26/speed-up-maven-builds-in-tekton-pipelines/) but I can't make the workspace use the pvc created.

I also tried to use the maven ClusterTask provided with the operator but got the same error for both of the workspaces needed (source, maven-settings).

This is my PipelineRun:
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: payara-micro-run
spec:
  pipelineRef:
    name: new-pipeline
  resources:
    - name: payara-repo
      resourceRef:
        name: git-twkxea
  workspaces:
  - name: maven-repo
    persistentVolumeClaim:
      claimName: maven-source-pvc
```

And this is the log from the TaskRun:
```
bound workspaces did not match declared workspaces: didn't provide required values: [maven-repo]
```
